name: CI x86_64

on: [push, pull_request, merge_group]
env:
  ARCH: x86_64
  CC: gcc
  CONTAINER_NAMESPACE: ghcr.io/opendataplane/odp-docker-images
  OS: ubuntu_24.04

jobs:
  Run_process_mode:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    env:
      CONF: "--enable-dpdk"
    steps:
      - uses: actions/checkout@v6
      - run: sudo docker run -i -v `pwd`:/odp --privileged --shm-size 8g -e CC="${CC}" -e ARCH="${ARCH}"
               -e CONF="${CONF}" -e ODP_CONFIG_FILE=/odp/platform/linux-generic/test/process-mode.conf
               -e ODPH_PROC_MODE=1 $CONTAINER_NAMESPACE/odp-ci-${OS}-${ARCH} /odp/scripts/ci/check.sh
      - if: ${{ failure() }}
        uses: ./.github/actions/run-failure-log
